# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:

name: setup-geospatial
run-name: Test the setup-geospatial action

permissions: write-all


defaults:
  run:
    shell: bash -l {0}

jobs:
  setup-geospatial:
    name: setup-geospatial
    runs-on: macos-latest
    steps:
      - uses: mt-climate-office/actions/setup-geospatial@v1
      
      - name: run
        run: |
          Rscript -e 'library(sf); print(sf::sf_extSoftVersion())'
