# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:

name: update
run-name: Update the USDM Archive with the latest data! ðŸš€

permissions: write-all

jobs:
  setup-geospatial:
    name: setup-geospatial
    runs-on: macos-latest
    steps:
      - uses: mt-climate-office/actions/setup-geospatial@v1
